In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder,OneHotEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('../data/hr.csv')

In [3]:
num_cols = df.select_dtypes(include=['int64','float64']).columns

print(num_cols)

Index(['Age', 'DailyRate', 'HomeDist', 'Education', 'EnvironmentSatisfaction',
       'HourlyRate', 'JobInvolvement', 'JobLvl', 'JobSatisfaction',
       'MonthlyInc', 'MonthlyRate', 'NumCompaniesWorked', 'SalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'Work_Life_Bal',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition'],
      dtype='str')

In [4]:
cat_cols = df.select_dtypes(include='object').columns

print(cat_cols)

Index([], dtype='str')

In [5]:
df

,Age,DailyRate,HomeDist,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLvl,JobSatisfaction,MonthlyInc,...,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,Marital_Married,Marital_Single,OverTime_Yes,Attrition
0,41,1102,1,2,2,94,3,2,4,5993,...,False,False,False,False,True,False,False,True,True,1
1,49,279,8,1,3,61,2,2,2,5130,...,False,False,False,True,False,False,True,False,False,0
2,37,1373,2,2,4,92,2,1,3,2090,...,False,False,False,False,False,False,False,True,True,1
3,33,1392,3,4,4,56,3,1,3,2909,...,False,False,False,True,False,False,True,False,True,0
4,27,591,2,1,1,40,3,1,2,3468,...,False,False,False,False,False,False,True,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351,36,884,23,2,3,41,4,2,4,2571,...,False,False,False,False,False,False,True,False,False,0
1352,39,613,6,1,4,42,2,3,1,9991,...,False,False,False,False,False,False,True,False,False,0
1353,27,155,4,3,2,87,4,2,2,6142,...,False,True,False,False,False,False,True,False,True,0
1354,49,1023,2,3,4,63,2,2,2,5390,...,False,False,False,False,True,False,True,False,False,0
1355,34,628,8,3,2,82,4,2,3,4404,...,False,False,False,False,False,False,True,False,False,0

In [6]:
df.columns

Index(['Age', 'DailyRate', 'HomeDist', 'Education', 'EnvironmentSatisfaction',
       'HourlyRate', 'JobInvolvement', 'JobLvl', 'JobSatisfaction',
       'MonthlyInc', 'MonthlyRate', 'NumCompaniesWorked', 'SalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'Work_Life_Bal',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Travel_Travel_Frequently',
       'Travel_Travel_Rarely', 'Dept_Research & Development', 'Dept_Sales',
       'EduField_Life Sciences', 'EduField_Marketing', 'EduField_Medical',
       'EduField_Other', 'EduField_Technical Degree', 'Gender_Male',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'Marital_Married', 'Marital_Single', 'OverTime_Yes', 'Attrition'],
      dtype='str')

In [7]:
df.drop(['Over18','EmpNo','StdHours','EmpCount'],
        axis=1,
        inplace=True,
        errors='ignore')

In [8]:
df.columns

Index(['Age', 'DailyRate', 'HomeDist', 'Education', 'EnvironmentSatisfaction',
       'HourlyRate', 'JobInvolvement', 'JobLvl', 'JobSatisfaction',
       'MonthlyInc', 'MonthlyRate', 'NumCompaniesWorked', 'SalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'Work_Life_Bal',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Travel_Travel_Frequently',
       'Travel_Travel_Rarely', 'Dept_Research & Development', 'Dept_Sales',
       'EduField_Life Sciences', 'EduField_Marketing', 'EduField_Medical',
       'EduField_Other', 'EduField_Technical Degree', 'Gender_Male',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'Marital_Married', 'Marital_Single', 'OverTime_Yes', 'Attrition'],
      dtype='str')

In [9]:
df.head()

,Age,DailyRate,HomeDist,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLvl,JobSatisfaction,MonthlyInc,...,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,Marital_Married,Marital_Single,OverTime_Yes,Attrition
0,41,1102,1,2,2,94,3,2,4,5993,...,False,False,False,False,True,False,False,True,True,1
1,49,279,8,1,3,61,2,2,2,5130,...,False,False,False,True,False,False,True,False,False,0
2,37,1373,2,2,4,92,2,1,3,2090,...,False,False,False,False,False,False,False,True,True,1
3,33,1392,3,4,4,56,3,1,3,2909,...,False,False,False,True,False,False,True,False,True,0
4,27,591,2,1,1,40,3,1,2,3468,...,False,False,False,False,False,False,True,False,False,0

In [11]:
df['Attrition'].value_counts()

Attrition
0    1124
1     232
Name: count, dtype: int64

In [12]:
cat_cols = df.select_dtypes(include='object').columns
print(cat_cols)

Index([], dtype='str')

In [ ]:
df = pd.get_dummies(df,
                    columns=cat_cols,
                    drop_first=True)
#used for one hot encoding
#columns:convert these specific columns to numeric value
#drop_first:remove redundant data

In [14]:
df.head()

,Age,DailyRate,HomeDist,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLvl,JobSatisfaction,MonthlyInc,...,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,Marital_Married,Marital_Single,OverTime_Yes,Attrition
0,41,1102,1,2,2,94,3,2,4,5993,...,False,False,False,False,True,False,False,True,True,1
1,49,279,8,1,3,61,2,2,2,5130,...,False,False,False,True,False,False,True,False,False,0
2,37,1373,2,2,4,92,2,1,3,2090,...,False,False,False,False,False,False,False,True,True,1
3,33,1392,3,4,4,56,3,1,3,2909,...,False,False,False,True,False,False,True,False,True,0
4,27,591,2,1,1,40,3,1,2,3468,...,False,False,False,False,False,False,True,False,False,0

In [15]:
X = df.drop('Attrition', axis=1)

y = df['Attrition']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
#Using stratify=y ensures both the training and testing
#  datasets have a similar proportion of employees who left and stayed.

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1084, 44)
(272, 44)
(1084,)
(272,)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)#fit_transform() on the training data to calculate and apply the scaling parameters

X_test = scaler.transform(X_test)#transform() on the test data so that it is scaled using the same parameters learned from the training data, avoiding data leakage.

#as the numeric value of diff columns is diff :
#therefore standard scalar standardize ech numeric feature

In [19]:
import joblib
#joblib:used to save obj(model,scalar,encoder)and load
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [ ]:
#create the final processed dataset and save it as a CSV file
processed_df = pd.DataFrame(X)

processed_df['Attrition'] = y

processed_df.to_csv(
    "../data/hr.csv",
    index=False
)

In [21]:
print(df.head())
print(df.shape)
print(df.columns)

   Age  DailyRate  HomeDist  Education  EnvironmentSatisfaction  HourlyRate  \
0   41       1102         1          2                        2          94
1   49        279         8          1                        3          61
2   37       1373         2          2                        4          92
3   33       1392         3          4                        4          56
4   27        591         2          1                        1          40

   JobInvolvement  JobLvl  JobSatisfaction  MonthlyInc  ...  JobRole_Manager  \
0               3       2                4        5993  ...            False
1               2       2                2        5130  ...            False
2               2       1                3        2090  ...            False
3               3       1                3        2909  ...            False
4               3       1                2        3468  ...            False

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                           False                      False
1                           False                      False
2                           False                      False
3                           False                      False
4                           False                      False

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                       False                     True
1                        True                    False
2                       False                    False
3                        True                    False
4                       False                    False

   JobRole_Sales Representative  Marital_Married  Marital_Single  \
0                         False            False            True
1                         False             True           False
2                         False            False            True
3                         False             True           False
4                         False             True           False

   OverTime_Yes  Attrition
0          True          1
1         False          0
2          True          1
3          True          0
4         False          0

[5 rows x 45 columns]
(1356, 45)
Index(['Age', 'DailyRate', 'HomeDist', 'Education', 'EnvironmentSatisfaction',
       'HourlyRate', 'JobInvolvement', 'JobLvl', 'JobSatisfaction',
       'MonthlyInc', 'MonthlyRate', 'NumCompaniesWorked', 'SalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'Work_Life_Bal',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Travel_Travel_Frequently',
       'Travel_Travel_Rarely', 'Dept_Research & Development', 'Dept_Sales',
       'EduField_Life Sciences', 'EduField_Marketing', 'EduField_Medical',
       'EduField_Other', 'EduField_Technical Degree', 'Gender_Male',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'Marital_Married', 'Marital_Single', 'OverTime_Yes', 'Attrition'],
      dtype='str')

In [24]:
import joblib

joblib.dump(X_train, "../data/X_train.pkl")
joblib.dump(X_test, "../data/X_test.pkl")
joblib.dump(y_train, "../data/y_train.pkl")
joblib.dump(y_test, "../data/y_test.pkl")

['../data/y_test.pkl']